#!/usr/bin/env bash
# Copy bundled MCP servers from Ryan's local trees (read-only source), strip build products and secrets, record provenance.
set -eu
cd "$(dirname "$0")"
RM="/Users/ryan_/Documents/Claude Code Repo/revenue-manager-next"
KIE="$HOME/.claude/skills/solnest-install-kie-mcp/resources"
# rsync: first matching rule wins, so .env.example is whitelisted before the .env.* exclude that would otherwise swallow it.
EX=(--include=.env.example --exclude=.env --exclude='.env.*' --exclude=session.txt --exclude=node_modules --exclude=dist --exclude=.venv --exclude=__pycache__ --exclude='*.pyc' --exclude=.DS_Store --exclude=.cache --exclude=.pytest_cache)
mkdir -p mcp-servers
for s in hospitable pricelabs turno airroi; do
  rm -rf "mcp-servers/$s"; rsync -a "${EX[@]}" "$RM/mcp-servers/$s/" "mcp-servers/$s/"
  [ -f "mcp-servers/$s/.env.example" ] || { echo "missing .env.example in $s"; exit 1; }
  grep -q '^\.env$' "mcp-servers/$s/.gitignore" 2>/dev/null || printf '.env\n.env.*\n!.env.example\nnode_modules/\ndist/\n.venv/\n__pycache__/\n' >> "mcp-servers/$s/.gitignore"
done
rm -rf mcp-servers/kie; mkdir -p mcp-servers/kie
cp "$KIE/server.py" "$KIE/models.json" "$KIE/requirements.txt" mcp-servers/kie/
printf 'KIE_API_KEY=\n' > mcp-servers/kie/.env.example
# PIN: both airroi and kie import mcp.server.fastmcp, which was removed in mcp 2.x (verified 2026-09-21: fresh install of unpinned 'mcp' fails on import).
printf 'httpx\nmcp>=1.2,<2\npython-dotenv\n' > mcp-servers/airroi/requirements.txt
printf 'mcp[cli]>=1.2,<2\n' > mcp-servers/kie/requirements.txt
printf '.env\n.env.*\n!.env.example\n.venv/\n__pycache__/\n' > mcp-servers/kie/.gitignore
# build/*.md are NOT synced. They were seeded from $RM once, then curated in this repo
# (em-dashes removed, register lines moved to lib/mcp_register.py, handoff section added).
# Re-copying from $RM would silently undo that (it did, 2026-09-22). Only warn if upstream drifts.
for b in build-pms-mcp.md build-pricing-ops-mcp.md; do
  if [ -f "$RM/$b" ] && [ -f "build/$b" ] && ! diff -q "$RM/$b" "build/$b" >/dev/null 2>&1; then
    echo "note: $RM/$b differs from build/$b (expected: build/ is curated). Diff by hand if RM shipped a real change."
  fi
done
# Force TURNO_ENV example to production for the summit
sed -i.bak 's/^TURNO_ENV=.*/TURNO_ENV=production/' mcp-servers/turno/.env.example && rm -f mcp-servers/turno/.env.example.bak
{
  echo "# Bundled server provenance (generated by sync-bundled-servers.sh)"
  echo "synced: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "revenue-manager-next path: $RM"
  echo "commit: $(git -C "$RM" rev-parse HEAD)"
  echo "dirty: $([ -n "$(git -C "$RM" status --porcelain)" ] && echo yes || echo no)"
  echo "kie source: $KIE (skill resources)"
  echo "servers: hospitable pricelabs turno airroi kie"
  echo "note: rankbreeze cookie server intentionally not bundled (official MCP used instead)"
} > mcp-servers/SOURCES.md
echo "synced. re-run before every release."
